var hierarchy =
[
    [ "ActiveQuest", "class_active_quest.html", null ],
    [ "ChangeBuildType.BuildPanel", "struct_change_build_type_1_1_build_panel.html", null ],
    [ "GridData", "class_grid_data.html", null ],
    [ "GridDataSave", "class_grid_data_save.html", null ],
    [ "GridEntry", "class_grid_entry.html", null ],
    [ "IBeginDragHandler", null, [
      [ "QuestUIManager", "class_quest_u_i_manager.html", null ]
    ] ],
    [ "IDragHandler", null, [
      [ "QuestUIManager", "class_quest_u_i_manager.html", null ]
    ] ],
    [ "IEndDragHandler", null, [
      [ "QuestUIManager", "class_quest_u_i_manager.html", null ]
    ] ],
    [ "JY.IRoomDetector", "interface_j_y_1_1_i_room_detector.html", null ],
    [ "MonoBehaviour", null, [
      [ "BGMManager", "class_b_g_m_manager.html", null ],
      [ "CameraCon", "class_camera_con.html", null ],
      [ "ChangeBuildType", "class_change_build_type.html", null ],
      [ "ChangeFloorSystem", "class_change_floor_system.html", null ],
      [ "EscUI", "class_esc_u_i.html", null ],
      [ "FlowCloudSystem", "class_flow_cloud_system.html", null ],
      [ "GameManager", "class_game_manager.html", null ],
      [ "GraphicSetting", "class_graphic_setting.html", null ],
      [ "IngameFadeSystem", "class_ingame_fade_system.html", null ],
      [ "InitializeFirstButton", "class_initialize_first_button.html", null ],
      [ "InputManager", "class_input_manager.html", null ],
      [ "JY.AIAgent", "class_j_y_1_1_a_i_agent.html", null ],
      [ "JY.AISpawner", "class_j_y_1_1_a_i_spawner.html", null ],
      [ "JY.AutoNavMeshBaker", "class_j_y_1_1_auto_nav_mesh_baker.html", null ],
      [ "JY.CounterManager", "class_j_y_1_1_counter_manager.html", null ],
      [ "JY.FurnitureID", "class_j_y_1_1_furniture_i_d.html", null ],
      [ "JY.PaymentSystem", "class_j_y_1_1_payment_system.html", null ],
      [ "JY.ReputationSystem", "class_j_y_1_1_reputation_system.html", null ],
      [ "JY.RoomContents", "class_j_y_1_1_room_contents.html", null ],
      [ "JY.RoomManager", "class_j_y_1_1_room_manager.html", null ],
      [ "JY.ShipController", "class_j_y_1_1_ship_controller.html", null ],
      [ "JY.ShipObjectPool", "class_j_y_1_1_ship_object_pool.html", null ],
      [ "JY.ShipSystem", "class_j_y_1_1_ship_system.html", null ],
      [ "JY.TimeManager", "class_j_y_1_1_time_manager.html", null ],
      [ "JY.TimeSystem", "class_j_y_1_1_time_system.html", null ],
      [ "LanguageUI", "class_language_u_i.html", null ],
      [ "LoadingSystem", "class_loading_system.html", null ],
      [ "ObjectInteractionUI", "class_object_interaction_u_i.html", null ],
      [ "ObjectPlacer", "class_object_placer.html", null ],
      [ "PerformanceMonitor", "class_performance_monitor.html", null ],
      [ "PlacementSystem", "class_placement_system.html", null ],
      [ "PlayerWallet", "class_player_wallet.html", null ],
      [ "QuestLogItem", "class_quest_log_item.html", null ],
      [ "QuestLogUI", "class_quest_log_u_i.html", null ],
      [ "QuestManager", "class_quest_manager.html", null ],
      [ "QuestUIManager", "class_quest_u_i_manager.html", null ],
      [ "SFXManager", "class_s_f_x_manager.html", null ],
      [ "SaveManager", "class_save_manager.html", null ],
      [ "SettingUI", "class_setting_u_i.html", null ],
      [ "SoundSetting", "class_sound_setting.html", null ],
      [ "SpawnEffect", "class_spawn_effect.html", null ],
      [ "SunMoonController", "class_sun_moon_controller.html", null ],
      [ "TimeControlScript", "class_time_control_script.html", null ],
      [ "UIController", "class_u_i_controller.html", null ],
      [ "UnlockSystem", "class_unlock_system.html", null ],
      [ "VisualizationMoney", "class_visualization_money.html", null ]
    ] ],
    [ "ObjectData", "class_object_data.html", null ],
    [ "JY.PaymentSystem.PaymentInfo", "class_j_y_1_1_payment_system_1_1_payment_info.html", null ],
    [ "PlacementData", "class_placement_data.html", null ],
    [ "JY.PoolStatus", "struct_j_y_1_1_pool_status.html", null ],
    [ "SaveData", "class_save_data.html", null ],
    [ "ScriptableObject", null, [
      [ "ObjectsDatabaseSO", "class_objects_database_s_o.html", null ],
      [ "QuestData", "class_quest_data.html", null ]
    ] ],
    [ "JY.ShipRoute", "class_j_y_1_1_ship_route.html", null ],
    [ "JY.ShipSchedule", "class_j_y_1_1_ship_schedule.html", null ],
    [ "UnlockableItem", "class_unlockable_item.html", null ]
];